title: Distributed Systems
show_downloads: false

google_analytics: UA-110186108-1
theme: jekyll-theme-hacker
description              : "Self-study Materials"
url                      : "https://andresnamm.github.io" # the base hostname & protocol for your site e.g. "https://mmistakes.github.io"
baseurl                  : "/DS-teaching" # the subpath of your site, e.g. "/blog"



# Defaults
defaults:
  # _tutorials
  - scope:
      path: ""
      type: ds
    values:
      layout: default
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      incmath: true
  # _sysadm
  - scope:
      path: ""
      type: sysadm
    values:
      layout: default
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      incmath: true
  - scope:
    # _datasec
      path: ""
      type: datasec
    values:
      layout: default
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      incmath: true
  # _trivia
  - scope:
      path: ""
      type: trivia
    values:
      layout: default
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      incmath: true


# Collections
collections:
  ds:
    output: true
    permalink: /:collection/:path/
  sysadm:
    output: true
    permalink: /:collection/:path/
  datasec:
    output: true
    permalink: /:collection/:path/
  trivia:
    output: true
    permalink: /:collection/:path/
